version: "3.9"
services:
  node-discovery:
    # build image with "docker build --tag evoting_node-discovery ./node_discovery"
    image: "evoting_node-discovery"
    ports:
      - 9999:9999
  connector:
    # build image with "docker build --tag evoting_connector ./connector"
    image: "evoting_connector"
    ports:
      - 1234:1234
    environment: 
      - ND_ADDR=node-discovery:9999
  node-1:
    # build image with "docker build --tag evoting_node ."
    image: "evoting_node"
    ports:
      - 1337:1337
    depends_on: 
      - node-discovery
    environment: 
      - HOSTNAME=node-1
      - DISCOVERY_ADDR=node-discovery:9999
  node-2:
    image: "evoting_node"
    ports:
      - 1338:1338
    depends_on: 
      - node-discovery
      - node-1
    # entrypoint changed so that ports remain the same as on localhost
    entrypoint: ["/evoting", "-consensus=pbft", "-port=1338"]
    environment: 
      - HOSTNAME=node-2
      - DISCOVERY_ADDR=node-discovery:9999
  client-1:
    image: "evoting_node"
    ports:
      - 2001:2001
    depends_on: 
      - node-discovery
    entrypoint: ["/evoting", "-client_mode=true", "-port=2001"]
    environment: 
      - HOSTNAME=client-1
      - DISCOVERY_ADDR=node-discovery:9999
